language: java
# https://docs.travis-ci.com/user/database-setup/#mysql
# https://docs.travis-ci.com/user/customizing-the-build/#build-matrix
matrix:
    include:
        - os: linux
          dist: precise # mysql 5.5
          jdk: oraclejdk8
          env: MySqlVer=55
        - os: linux
          dist: trusty # mysql 5.6
          jdk: oraclejdk11
          env: MySqlVer=56
        - os: linux
          dist: xenial # mysql 5.7
          jdk: oraclejdk11
          env: MySqlVer=57
        - os: linux
          dist: xenial # mysql 5.7
          jdk: openjdk11
          env: MySqlVer=57

script: mvn verify
services: mysql
before_script:
  - mysql -e "SET GLOBAL sql_mode='';"
  - mysql --version
  - mysql -e "DROP DATABASE IF EXISTS makumba;" # TEMP to make sure it is empty
  - mysql -e "CREATE DATABASE IF NOT EXISTS makumba;"

  # TEMP - populate DB to avoid "Table definition has changed, please retry transaction" during tests
  - if [ "$MySqlVer" -ge "56" ]; then echo "DB restore for MySql $MySqlVer"; mysql makumba < ci/makumba-test.sql; fi
  - 'cd makumba-parent'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: ZNARLraxMVbMTgyybVPCAegM9YODhrgpQu4e+hn8mkuiAis2r77/tbHt31fIOAOnQzmbTw+4hl+BvHmsb4RzSmEgUxcp4VfAFh1Yp/iWH+Xljcfsq5rPJKqUIoQRmh5SHr3FiwFrQ4vqbymsnQx5pWeCIS6odWfQ8fDKJVq6orJ5bE+hLGmxXu83Oxr4jfnF54YJwDpDE3INoL/x7qzSagVkxh65K/NElzDfqDhh1PLJL2AWdgUz2nSZk+4wvkilwC2+ga0inzwwgDIzgBNYhqFwW8fqjjAQvl9wqHb/MqipLUHkMt9hJNhhkdPTGTLYKI4ho4itqqOgfJKy+6K1nF4DFqtHMhyzcSXQm2O/B2MolOt3B8nUuAhDElxG+JyAz/sLjltfK0ZHHzxOO8h20EIg9ddWPz2nZZF0sF6yqVE6fQsyjmOfgy9QWK0IqoatdXWanmqn0XX11AQeOjX8JmOhi9DCrhwkb55pDvBsAf5/wQsecR7aoF4B7guzClGgWolC49aWuLdrOQATH60NSEQfPIkKeN9h9u33ZAts/TJ6R37lUo5r6CIIJwrwxd5t98R25kfemnRHgO+CQOfeFgy9DrsX4SE2IK5WFNeTgtPmb4Q26sTXMoGylsmiEuCiYefI0CmfY+3VKkB9T1cULYrMqC9Ip2YBpq0UzxC8hGo=
