package org.makumba.devel;

import java.util.Properties;

/**
 * This class defines a template for JSP files generated by the code generator. Templates are stored and read from
 * {@link Properties} files. Makumba defines some code templates internally; custom templates can be defined by users
 * and put into a directory called <code>codeTemplates</code> in the classes path of the web application.
 * 
 * @author rudi
 * @version $Id$
 */
public class CodeGeneratorTemplate {
    static final String DEFAULT_STYLE_HEADER = "<%@ taglib uri=\"http://www.makumba.org/presentation\" prefix=\"mak\" %>\n"
            + "<%@ taglib uri=\"http://java.sun.com/jstl/core_rt\" prefix=\"c\" %>\n";

    String afterField;

    String afterFieldName;

    String afterFieldTag;

    String afterFormBegin;

    String beforeField;

    String beforeFieldName;

    String beforeFieldTag;

    String beforeFormEnd;

    String footer;

    String header;

    String beforePageHeader;

    String afterPageHeader;

    String beforePageHeaderLevel2;

    String afterPageHeaderLevel2;

    public CodeGeneratorTemplate() {
    }

    public CodeGeneratorTemplate(Properties props) {
        header = (String) props.getProperty("header", DEFAULT_STYLE_HEADER);
        footer = (String) props.getProperty("footer", "");
        afterFormBegin = (String) props.getProperty("afterFormBegin", "");
        beforeFormEnd = (String) props.getProperty("beforeFormEnd", "");
        beforeField = (String) props.getProperty("beforeField", "");
        afterField = (String) props.getProperty("afterField", "");
        beforeFieldName = (String) props.getProperty("beforeFieldName", "");
        afterFieldName = (String) props.getProperty("afterFieldName", "");
        beforeFieldTag = (String) props.getProperty("beforeFieldTag", "");
        afterFieldTag = (String) props.getProperty("afterFieldTag", "");
        beforePageHeader = (String) props.getProperty("beforePageHeader", "");
        afterPageHeader = (String) props.getProperty("afterPageHeader", "");
        beforePageHeaderLevel2 = (String) props.getProperty("beforePageHeaderLevel2", beforePageHeader);
        afterPageHeaderLevel2 = (String) props.getProperty("afterPageHeaderLevel2", afterPageHeader);
    }
}
