/*
 * generated by Xtext
 */
package org.makumba.devel.eclipse.mdd.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an
 * example
 */
public class MDDFormatter extends AbstractDeclarativeFormatter {

	@Override
	protected void configureFormatting(FormattingConfig c) {
		//org.makumba.devel.eclipse.mdd.services.MDDGrammarAccess f = (org.makumba.devel.eclipse.mdd.services.MDDGrammarAccess) getGrammarAccess();
	}
}
