/*
* generated by Xtext
*/
package org.makumba.devel.eclipse.mdd.ui.labeling;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class MDDDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

	@Inject
	private ILabelProvider labelProvider;

	//TODO: finish this
	public String image(IResourceDescription element) {
		return "DataDefinition16.png";
	}

	public String text(IEObjectDescription ele) {
		return ele.getName() + " - " + ele.getEClass().getName();
	}

	public Object image(IEObjectDescription ele) {
		return labelProvider.getImage(ele.getEObjectOrProxy());
	}

}
