<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MDD"
    nsURI="http://www.makumba.org/devel/plugin/eclipse/mdd/MDD" nsPrefix="MDD">
  <eClassifiers xsi:type="ecore:EClass" name="DataDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="d" upperBound="-1" eType="#//Declaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldComment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" eType="#//Modifiers"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedef" eType="#//FieldType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modifiers">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notNull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notEmpty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDec" eType="#//TypeDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntEnum" eSuperTypes="#//FieldType #//FunctionArgumentBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//EnumValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharEnum" eSuperTypes="#//FieldType #//FunctionArgumentBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decpricated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharType" eSuperTypes="#//FieldType #//FunctionArgumentBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointerType" eSuperTypes="#//FieldType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//DataDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//FieldType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//DataDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubFieldDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFieldOf" eType="#//FieldDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="d" eType="#//Declaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TitleDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FieldPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//FunctionCall"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedNamespace" eType="#//DataDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldType" eType="#//FieldType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationRuleDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorMessage" eType="#//ErrorMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonValidationRuleDeclaration"
      eSuperTypes="#//ValidationRuleDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//FunctionArguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparisonExp" eType="#//ComparisonExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//ComparisonPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="o" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//ComparisonPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FieldPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="df" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="u" eType="#//UpperFunction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l" eType="#//LowerFunction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="d" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpperFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FieldPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowerFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FieldPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeValidationRuleDeclaration" eSuperTypes="#//ValidationRuleDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//FieldReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//Range"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegexValidationRuleDeclaration" eSuperTypes="#//ValidationRuleDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//FieldReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="f" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="t" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniquenessValidationRuleDeclaration"
      eSuperTypes="#//ValidationRuleDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//FunctionArguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorMessage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NativeValidationRuleDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FieldDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//FunctionArgumentDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//FunctionBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m" eType="#//ErrorMessage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionArgumentDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="f" upperBound="-1" eType="#//FunctionArgumentBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionArgumentBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//FunctionDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="f" eType="#//FunctionArguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldPath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FieldDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subField" eType="#//FieldPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FieldDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionArguments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//FieldPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnionRule" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="q" upperBound="-1" eType="#//QueryRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryRule" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectFrom" eSuperTypes="#//QueryRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//WhereClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupBy" eType="#//GroupByClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderBy" eType="#//OrderByClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//SelectClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//FromClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//SelectedPropertiesList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="n" eType="#//NewExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//SelectedPropertiesList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRange" upperBound="-1"
        eType="#//FromRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromJoin" upperBound="-1"
        eType="#//FromJoin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromJoin"/>
  <eClassifiers xsi:type="ecore:EClass" name="WithClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromClassOrOuterQueryPath" eSuperTypes="#//FromJoin #//FromRange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="w" eType="#//WithClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyFetch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InCollectionElementsDeclaration" eSuperTypes="#//FromRange"/>
  <eClassifiers xsi:type="ecore:EClass" name="GroupByClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" upperBound="-1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="h" eType="#//HavingClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderByClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="o" upperBound="-1" eType="#//OrderElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="HavingClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectedPropertiesList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" upperBound="-1" eType="#//AliasedExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AliasedExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//OrderElement #//AliasedExpression #//ExpressionOrVector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="v" eType="#//VectorExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalOrExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="l" upperBound="-1" eType="#//LogicalAndExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalAndExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="n" upperBound="-1" eType="#//NegatedExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegatedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="n" eType="#//NegatedExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EqualityExpression" eSuperTypes="#//NegatedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" upperBound="-1" eType="#//RelationalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LikeEscape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" eType="#//Concatenation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BetweenList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" upperBound="-1" eType="#//Concatenation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concatenation" eSuperTypes="#//RelationalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" upperBound="-1" eType="#//AdditiveExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="i" eType="#//CompoundExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BetweenList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" eType="#//Concatenation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l" eType="#//LikeEscape"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveExpression" eSuperTypes="#//Concatenation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m" upperBound="-1" eType="#//MultiplyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplyExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="u" upperBound="-1" eType="#//UnaryExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="u" eType="#//UnaryExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaseExpression" eSuperTypes="#//UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="w" upperBound="-1" eType="#//WhenClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="#//ElseClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" upperBound="-1" eType="#//AltWhenClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenExpr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpr" eType="#//UnaryExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AltWhenClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="w" eType="#//UnaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t" eType="#//UnaryExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="u" eType="#//UnaryExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifiedExpression" eSuperTypes="#//UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//UnionRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prime" eType="#//PrimaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" upperBound="-1" eType="#//ExprList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionOrVector" eSuperTypes="#//PrimaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="VectorExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentPrimary" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="#//ExprList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregate" eSuperTypes="#//IdentPrimary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" eType="#//AdditiveExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" upperBound="-1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//UnionRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" upperBound="-1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
