
/*
 * generated by Xtext
 */
 
package org.makumba.devel.eclipse.mdd.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class MDDExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.makumba.devel.eclipse.mdd.ui.internal.MDDActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.makumba.devel.eclipse.mdd.ui.internal.MDDActivator.getInstance().getInjector("org.makumba.devel.eclipse.mdd.MDD");
	}
	
}
