/*
 * generated by Xtext
 */
package org.makumba.devel.eclipse.mdd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;
import org.makumba.devel.eclipse.mdd.ui.codegenerator.MakumbaJSPCodeGenerator;
import org.makumba.devel.eclipse.mdd.ui.hyperlinking.MQLHyperlinkHelper;
import org.makumba.devel.eclipse.mdd.ui.syntaxcoloring.AntlrTokenToAttributeIdMapper;
import org.makumba.devel.eclipse.mdd.ui.syntaxcoloring.SemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MDDUiModule extends org.makumba.devel.eclipse.mdd.ui.AbstractMDDUiModule {
	public MDDUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return AntlrTokenToAttributeIdMapper.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHiglightingCalculator() {
		return SemanticHighlightingCalculator.class;
	}

	@Override
	public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
		return org.eclipse.xtext.ui.editor.IXtextEditorCallback.NullImpl.class;
	}

	public Class<? extends MakumbaJSPCodeGenerator> bindMakumbaJSPCodeGenerator() {
		return org.makumba.devel.eclipse.mdd.ui.codegenerator.MakumbaJSPCodeGenerator.class;
	}

	public Class<? extends IHyperlinkHelper> bindHyperlink() {
		return MQLHyperlinkHelper.class;
	}

}
