/*
 * generated by Xtext
 */
package org.makumba.devel.eclipse.mdd;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.makumba.devel.eclipse.mdd.naming.MDDQualifiedNameProvider;
import org.makumba.devel.eclipse.mdd.validation.MQLValidator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MDDRuntimeModule extends org.makumba.devel.eclipse.mdd.AbstractMDDRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		// TODO Auto-generated method stub
		return MDDValueConverter.class;
	}

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		// TODO Auto-generated method stub
		return MDDQualifiedNameProvider.class;
	}

	public Class<? extends MDDUtils> bindMDDUtils() {
		return MDDUtils.class;
	}

	public Class<? extends MQLValidator> bindMQLValidator() {
		return MQLValidator.class;
	}
}
